# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_z4aLS90olqnGyd5lBWFwVNrQMISh6Tk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# =================================================================
# PROJETO: SISTEMA DE INTELIGÊNCIA DE VENDAS (LIVRARIA)
# OBJETIVO: Limpeza, integração de dados e análise de performance
# =================================================================

# 1. CARGA E ESTRUTURAÇÃO DE DADOS
# Simulando a entrada de dados de vendas
dados_livros = {
    'genero': ['Ficção', ' História', 'Autoajuda'], # Erro proposital de espaço
    'vendas': [120, 80, 200],
    'preco_medio': [45.0, 50.0, 30.0]
}

df = pd.DataFrame(dados_livros)

# Adicionando novo registro com dado faltante (Simulando erro de sistema)
novo_livro = {'genero': 'Biografias', 'vendas': 50, 'preco_medio': np.nan}
df = df._append(novo_livro, ignore_index=True)

# 2. DATA CLEANING (LIMPEZA DE DADOS)
# Padronização de strings: remove espaços e converte para minúsculo
df['genero'] = df['genero'].str.strip().str.lower()

# Tratamento de valores nulos (Imputação de valor médio/padrão)
df['preco_medio'] = df['preco_medio'].fillna(40.0)

# 3. FEATURE ENGINEERING (CRIAÇÃO DE NOVAS MÉTRICAS)
df['faturamento'] = df['vendas'] * df['preco_medio']

# 4. DATA INTEGRATION (MERGE COM TABELA DE FORNECEDORES)
fornecedores = {
    'genero': ['ficção', 'história', 'autoajuda', 'biografias'],
    'distribuidora': ['Editora A', 'Editora B', 'Editora C', 'Editora D']
}
df_fornecedores = pd.DataFrame(fornecedores)
df_final = pd.merge(df, df_fornecedores, on='genero', how='left')

# 5. LÓGICA DE NEGÓCIO PERSONALIZADA
def classificar_desempenho(valor):
    """Classifica o nível de faturamento por categoria."""
    if valor >= 5000: return '💎 Diamante'
    elif valor >= 2000: return '🥇 Ouro'
    else: return '🥈 Prata'

def calc_imposto(linha):
    """Aplica alíquota diferenciada para o gênero autoajuda."""
    taxa = 0.05 if linha['genero'] == 'autoajuda' else 0.10
    return linha['faturamento'] * taxa

df_final['categoria'] = df_final['faturamento'].apply(classificar_desempenho)
df_final['imposto'] = df_final.apply(calc_imposto, axis=1)
df_final['lucro_liquido'] = df_final['faturamento'] - df_final['imposto']

# 6. EXIBIÇÃO DE RESULTADOS
print("=== RELATÓRIO ESTRATÉGICO DE VENDAS ===")
print(df_final[['genero', 'distribuidora', 'faturamento', 'categoria']])

# 7. VISUALIZAÇÃO DE DADOS
plt.style.use('ggplot')
faturamento_editora = df_final.groupby('distribuidora')['faturamento'].sum().sort_values()
faturamento_editora.plot(kind='barh', color='teal')
plt.title('Faturamento Total por Distribuidora')
plt.xlabel('Faturamento (R$)')
plt.show()

# --- 8. EXPORTAÇÃO DOS RESULTADOS ---

# Salvando a tabela detalhada em um arquivo Excel
df_final.to_excel('relatorio_vendas_final.xlsx', index=False)

# Caso queira salvar também o resumo por categoria em outra aba ou arquivo
resumo_final = df_final.groupby('categoria')[['faturamento', 'lucro_liquido']].sum()
resumo_final.to_excel('resumo_performance.xlsx')

print("\n✅ Arquivos Excel gerados com sucesso!")